# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50, unique=True)),
                ('number', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=10, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='account_me',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('monthend_indicator', models.CharField(max_length=3)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.account_info', to_field='identifier')),
            ],
        ),
        migrations.CreateModel(
            name='gl_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50, unique=True)),
                ('balancesheet_type', models.CharField(choices=[('asset', 'asset'), ('liability', 'liability'), ('income', 'income'), ('expense', 'expense')], max_length=10)),
                ('asset_type', models.CharField(blank=True, max_length=50, null=True)),
                ('asset_holder', models.CharField(blank=True, max_length=50, null=True)),
                ('asset_source', models.CharField(blank=True, max_length=50, null=True)),
                ('level_1_category', models.CharField(blank=True, max_length=50, null=True)),
                ('level_2_category', models.CharField(blank=True, max_length=50, null=True)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='investment_transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product', models.CharField(max_length=50)),
                ('product_description', models.CharField(max_length=50)),
                ('transaction_type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('exchange_rate', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('balancesheet_type', models.CharField(choices=[('asset', 'asset'), ('liability', 'liability'), ('income', 'income'), ('expense', 'expense')], max_length=10)),
                ('activity', models.CharField(max_length=50)),
                ('activity_category', models.CharField(blank=True, max_length=50, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.account_info', to_field='identifier')),
                ('gl_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.gl_info', to_field='identifier')),
            ],
        ),
        migrations.CreateModel(
            name='ledger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balancesheet_type', models.CharField(choices=[('asset', 'asset'), ('liability', 'liability'), ('income', 'income'), ('expense', 'expense')], max_length=10)),
                ('activity', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.account_info', to_field='identifier')),
                ('gl_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.gl_info', to_field='identifier')),
            ],
        ),
        migrations.CreateModel(
            name='parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_1', models.CharField(blank=True, max_length=50, null=True)),
                ('value_2', models.CharField(blank=True, max_length=50, null=True)),
                ('value_3', models.CharField(blank=True, max_length=50, null=True)),
                ('value_4', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('value_5', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
