# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='value_1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='parameter'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='text value 1'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='text value 2'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value_4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='number value'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value_5',
            field=models.DateField(blank=True, null=True, verbose_name='date value'),
        ),
    ]
