# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_auto_20151230_2116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'get_latest_by': 'date'},
        ),
    ]
