# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_auto_20151230_2334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account_info',
            options={'ordering': ['company', 'identifier'], 'verbose_name': 'account information', 'verbose_name_plural': 'account information'},
        ),
        migrations.AlterModelOptions(
            name='account_me',
            options={'ordering': ['account', 'date'], 'verbose_name': 'account month-end balance', 'verbose_name_plural': 'account month-end balance'},
        ),
        migrations.AlterModelOptions(
            name='gl_info',
            options={'ordering': ['balancesheet_type', 'level_1_category', 'level_2_category', 'identifier'], 'verbose_name': 'ledger account setting'},
        ),
        migrations.AlterModelOptions(
            name='journal',
            options={'ordering': ['date', 'reference']},
        ),
        migrations.AlterModelOptions(
            name='ledger',
            options={'ordering': ['balancesheet_type', 'gl_account'], 'verbose_name': 'general ledger', 'verbose_name_plural': 'general ledger'},
        ),
    ]
