# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_auto_20151230_2345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account_info',
            options={'ordering': ['company', 'identifier'], 'verbose_name': 'account information', 'verbose_name_plural': 'accounts information'},
        ),
        migrations.AlterModelOptions(
            name='account_me',
            options={'ordering': ['account', 'date'], 'verbose_name': 'account month-end balance', 'verbose_name_plural': 'accounts month-end balance'},
        ),
    ]
