# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_auto_20151230_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_me',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.account_info', to_field='identifier'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.account_info', to_field='identifier'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='gl_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.gl_info', to_field='identifier'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.account_info', to_field='identifier'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='gl_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.gl_info', to_field='identifier'),
        ),
    ]
