# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_auto_20151231_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='value_4',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True, verbose_name='number value'),
        ),
    ]
