# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0010_auto_20160102_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gl_info',
            options={'ordering': ['balancesheet_type', 'asset_type', 'level_1_category', 'level_2_category', 'identifier'], 'verbose_name': 'ledger account setting'},
        ),
        migrations.AlterField(
            model_name='gl_info',
            name='asset_holder',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='asset holder'),
        ),
        migrations.AlterField(
            model_name='gl_info',
            name='asset_source',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='asset source'),
        ),
        migrations.AlterField(
            model_name='gl_info',
            name='asset_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='asset type'),
        ),
        migrations.AlterField(
            model_name='gl_info',
            name='balancesheet_type',
            field=models.CharField(choices=[('asset', 'asset'), ('liability', 'liability'), ('income', 'income'), ('expense', 'expense')], max_length=10, verbose_name='ledger'),
        ),
        migrations.AlterField(
            model_name='gl_info',
            name='identifier',
            field=models.CharField(max_length=50, unique=True, verbose_name='GL account'),
        ),
        migrations.AlterField(
            model_name='gl_info',
            name='level_1_category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='category 1'),
        ),
        migrations.AlterField(
            model_name='gl_info',
            name='level_2_category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='category 2'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='balancesheet_type',
            field=models.CharField(choices=[('asset', 'asset'), ('liability', 'liability'), ('income', 'income'), ('expense', 'expense')], max_length=10, verbose_name='ledger type'),
        ),
    ]
