# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0011_auto_20160102_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_info',
            name='country',
            field=models.CharField(default='Singapore', max_length=50),
        ),
        migrations.AlterField(
            model_name='account_info',
            name='currency',
            field=models.CharField(default='SGD', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='account_info',
            name='identifier',
            field=models.CharField(max_length=50, unique=True, verbose_name='account'),
        ),
        migrations.AlterField(
            model_name='account_info',
            name='owner',
            field=models.CharField(default='Awai', max_length=50),
        ),
        migrations.AlterField(
            model_name='account_info',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
    ]
