# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0013_auto_20160102_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='last_update_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value_5',
            field=models.DateField(blank=True, default=b'2016-01-03', null=True, verbose_name='date value'),
        ),
    ]
