# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0014_auto_20160103_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='investment_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ticker')),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='current price')),
                ('current_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='current amount')),
                ('currency', models.CharField(blank=True, default='SGD', max_length=10, null=True)),
                ('profit_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='profit/loss')),
                ('commission', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dividend', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_profit_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='total profit/loss')),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['type', 'identifier'],
                'verbose_name': 'investment information',
                'verbose_name_plural': 'investment information',
            },
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value_5',
            field=models.DateField(blank=True, default=b'2016-01-06', null=True, verbose_name='date value'),
        ),
    ]
