# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0015_auto_20160106_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment_info',
            name='total_yield',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='total profit/loss'),
        ),
        migrations.AlterField(
            model_name='investment_info',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='total price paid'),
        ),
    ]
