# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0020_auto_20160109_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment_transaction',
            old_name='product_description',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='investment_transaction',
            old_name='product',
            new_name='transaction_type_1',
        ),
        migrations.RenameField(
            model_name='investment_transaction',
            old_name='transaction_type',
            new_name='transaction_type_2',
        ),
        migrations.AddField(
            model_name='investment_transaction',
            name='identifier',
            field=models.CharField(default='', max_length=50, verbose_name='ticker'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investment_transaction',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='investment_transaction',
            name='unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
