# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0021_auto_20160109_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investment_transaction',
            options={'ordering': ['date', 'identifier', 'transaction_type_1', 'transaction_type_1'], 'verbose_name': 'investment transaction', 'verbose_name_plural': 'investment transaction'},
        ),
    ]
