# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0022_auto_20160109_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment_transaction',
            name='identifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.investment_info', to_field='identifier'),
        ),
    ]
