# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0023_auto_20160109_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment_transaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='investment_transaction',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='investment_transaction',
            name='transaction_type_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='investment_transaction',
            name='transaction_type_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
