# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0025_auto_20160109_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment_transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='investment_transaction',
            name='currency',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='investment_transaction',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='investment_transaction',
            name='identifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.investment_info', to_field='identifier'),
        ),
        migrations.AlterField(
            model_name='investment_transaction',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='investment_transaction',
            name='transaction_type_1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='investment_transaction',
            name='transaction_type_2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='investment_transaction',
            name='unit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
