# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0026_auto_20160109_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment_info',
            name='amount',
        ),
        migrations.AddField(
            model_name='investment_info',
            name='last_updated_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='investment_info',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
