# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0028_auto_20160109_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='value_5',
            field=models.DateField(blank=True, default=b'2016-01-11', null=True, verbose_name='date value'),
        ),
    ]
