# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0029_auto_20160111_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='post_indicater',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
