# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0030_journal_post_indicater'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='post_indicater',
            new_name='post_indicator',
        ),
    ]
