# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-17 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0031_auto_20160111_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gl_info',
            name='identifier',
            field=models.CharField(max_length=50, verbose_name='GL account'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='gl_account',
            field=models.CharField(max_length=50, verbose_name='GL account'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='last_update_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='reference',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ledger',
            name='gl_account',
            field=models.CharField(max_length=50, verbose_name='GL account'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value_5',
            field=models.DateField(blank=True, default=b'2016-01-17', null=True, verbose_name='date value'),
        ),
        migrations.AlterUniqueTogether(
            name='gl_info',
            unique_together=set([('identifier', 'balancesheet_type')]),
        ),
    ]
