# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-17 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0032_auto_20160117_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment_info',
            name='unit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
