# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-17 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0033_auto_20160117_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment_info',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='investment_info',
            name='current_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='current amount'),
        ),
        migrations.AlterField(
            model_name='investment_info',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='current price'),
        ),
        migrations.AlterField(
            model_name='investment_info',
            name='dividend',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='investment_info',
            name='last_update_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='investment_info',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='investment_info',
            name='profit_loss',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='profit/loss'),
        ),
        migrations.AlterField(
            model_name='investment_info',
            name='total_profit_loss',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='total profit/loss'),
        ),
        migrations.AlterField(
            model_name='investment_info',
            name='total_yield',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='yield'),
        ),
    ]
