# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0034_auto_20160117_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment_info',
            name='sold_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value_5',
            field=models.DateField(blank=True, default=b'2016-01-23', null=True, verbose_name='date value'),
        ),
    ]
