# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-23 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0035_auto_20160123_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment_info',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
