# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-24 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0036_investment_info_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='month',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='year',
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value_5',
            field=models.DateField(blank=True, default=b'2016-01-24', null=True, verbose_name='date value'),
        ),
    ]
