# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-24 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0037_auto_20160124_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
