# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0038_auto_20160124_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='last_update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value_5',
            field=models.DateField(blank=True, default=b'2016-02-15', null=True, verbose_name='date value'),
        ),
    ]
