# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 03:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0040_auto_20160215_1133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={},
        ),
    ]
