# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-21 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0041_auto_20160215_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment_transaction',
            name='journal_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='journal_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value_5',
            field=models.DateField(blank=True, default=b'2016-02-21', null=True, verbose_name='date value'),
        ),
    ]
