# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0042_auto_20160221_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment_transaction',
            name='company',
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value_5',
            field=models.DateField(blank=True, default=b'2016-02-22', null=True, verbose_name='date value'),
        ),
    ]
