# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-05 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0043_auto_20160222_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='activity_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value_5',
            field=models.DateField(blank=True, default=b'2016-03-05', null=True, verbose_name='date value'),
        ),
    ]
