# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-09 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0044_auto_20160305_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_info',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value_5',
            field=models.DateField(blank=True, default=b'2016-03-09', null=True, verbose_name='date value'),
        ),
    ]
