# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-10 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0045_auto_20160309_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='cashflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rental', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('phone', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dividendcard', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value_5',
            field=models.DateField(blank=True, default=b'2016-03-10', null=True, verbose_name='date value'),
        ),
    ]
