# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-12 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0047_auto_20160311_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='account_info_m',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk_date', models.DateField()),
                ('identifier', models.CharField(max_length=50, unique=True, verbose_name='account')),
                ('number', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('owner', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['company', 'identifier'],
                'verbose_name': 'account information backup',
                'verbose_name_plural': 'accounts information backups',
            },
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value_5',
            field=models.DateField(blank=True, default=b'2016-03-12', null=True, verbose_name='date value'),
        ),
    ]
