# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-13 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0050_auto_20160313_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment_info',
            old_name='percetage',
            new_name='percentage',
        ),
    ]
