# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-20 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0053_auto_20160313_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='value_5',
            field=models.DateField(blank=True, default=b'2016-03-20', null=True, verbose_name='date value'),
        ),
    ]
