# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0056_auto_20160322_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='value_5',
            field=models.DateField(blank=True, default=b'2016-03-25', null=True, verbose_name='date value'),
        ),
    ]
