# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0057_auto_20160325_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='value_5',
            field=models.DateField(blank=True, default=b'2016-04-19', null=True, verbose_name='date value'),
        ),
    ]
