# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0059_auto_20160423_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='cashflow_m',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk_date', models.DateField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rental', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('phone', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dividendcard', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('saving', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
