# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-01 00:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0061_auto_20160426_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='journal_m',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk_date', models.DateField()),
                ('date', models.DateField()),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('gl_account', models.CharField(max_length=50, verbose_name='GL account')),
                ('balancesheet_type', models.CharField(choices=[('asset', 'asset'), ('liability', 'liability'), ('income', 'income'), ('expense', 'expense')], max_length=10)),
                ('activity', models.CharField(max_length=50)),
                ('activity_category', models.CharField(blank=True, max_length=50, null=True)),
                ('reference', models.CharField(max_length=100)),
                ('journal_id', models.CharField(blank=True, max_length=100, null=True)),
                ('last_update_date', models.DateField(auto_now=True, null=True)),
                ('post_indicator', models.CharField(blank=True, max_length=5, null=True)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.account_info', to_field='identifier')),
            ],
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value_5',
            field=models.DateField(blank=True, default=b'2016-05-01', null=True, verbose_name='date value'),
        ),
    ]
