# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-02 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0062_auto_20160501_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal_m',
            name='account',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='account'),
        ),
        migrations.AlterField(
            model_name='journal_m',
            name='activity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='journal_m',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='journal_m',
            name='balancesheet_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='journal_m',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='journal_m',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journal_m',
            name='gl_account',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='GL account'),
        ),
        migrations.AlterField(
            model_name='journal_m',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value_5',
            field=models.DateField(blank=True, default=b'2016-05-02', null=True, verbose_name='date value'),
        ),
    ]
