# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-02 01:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0063_auto_20160502_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal_m',
            old_name='account',
            new_name='account_id',
        ),
    ]
