# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-08 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0064_auto_20160502_0951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account_info',
            options={'ordering': ['company', 'identifier'], 'verbose_name': 'account detail', 'verbose_name_plural': 'account details'},
        ),
        migrations.AlterModelOptions(
            name='account_info_m',
            options={},
        ),
        migrations.AlterField(
            model_name='account_info',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=b'0', max_digits=6, null=True, verbose_name=b'account balance'),
        ),
        migrations.AlterField(
            model_name='account_info',
            name='company',
            field=models.CharField(max_length=50, verbose_name=b'company'),
        ),
        migrations.AlterField(
            model_name='account_info',
            name='country',
            field=models.CharField(default=b'Singapore', max_length=50, verbose_name=b'country'),
        ),
        migrations.AlterField(
            model_name='account_info',
            name='currency',
            field=models.CharField(default=b'SGD', max_length=10, verbose_name=b'currency'),
        ),
        migrations.AlterField(
            model_name='account_info',
            name='identifier',
            field=models.CharField(max_length=50, unique=True, verbose_name=b'account identifier'),
        ),
        migrations.AlterField(
            model_name='account_info',
            name='number',
            field=models.CharField(max_length=50, verbose_name=b'account number'),
        ),
        migrations.AlterField(
            model_name='account_info',
            name='owner',
            field=models.CharField(default=b'Awai', max_length=50, verbose_name=b'owner'),
        ),
        migrations.AlterField(
            model_name='account_info',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'remark'),
        ),
        migrations.AlterField(
            model_name='account_info',
            name='status',
            field=models.CharField(default=b'active', max_length=50, verbose_name=b'status'),
        ),
        migrations.AlterField(
            model_name='account_info',
            name='type',
            field=models.CharField(max_length=50, verbose_name=b'type'),
        ),
        migrations.AlterField(
            model_name='account_info_m',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='account_info_m',
            name='identifier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value_5',
            field=models.DateField(blank=True, default=b'2016-05-08', null=True, verbose_name='date value'),
        ),
    ]
