# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-08 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0065_auto_20160508_2238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashflow',
            options={'ordering': ['year', 'month'], 'verbose_name': 'cashflow', 'verbose_name_plural': ''},
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='dividendcard',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name=b'Citi_Dividend_Card'),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='phone',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name=b'4G_contract'),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='rental',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='saving',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow_m',
            name='dividendcard',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow_m',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow_m',
            name='phone',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow_m',
            name='rental',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow_m',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow_m',
            name='saving',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow_m',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value_5',
            field=models.DateField(blank=True, default=b'2016-05-09', null=True, verbose_name='date value'),
        ),
    ]
