# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0066_auto_20160509_0028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'verbose_name': 'journal', 'verbose_name_plural': ''},
        ),
        migrations.RemoveField(
            model_name='journal_m',
            name='account_id',
        ),
        migrations.AddField(
            model_name='journal_m',
            name='account',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='journal',
            name='balancesheet_type',
            field=models.CharField(choices=[(b'asset', b'asset'), (b'liability', b'liability'), (b'income', b'income'), (b'expense', b'expense')], max_length=50),
        ),
        migrations.AlterField(
            model_name='journal',
            name='currency',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='journal_m',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='journal_m',
            name='balancesheet_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='journal_m',
            name='currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='journal_m',
            name='gl_account',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='journal_m',
            name='last_update_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value_5',
            field=models.DateField(blank=True, default=b'2016-05-10', null=True, verbose_name='date value'),
        ),
    ]
