# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-21 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0068_auto_20160510_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='sats_article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.CharField(blank=True, max_length=500, null=True, verbose_name=b'description')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name=b'end date')),
                ('ror', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name=b'ROR')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to=b'', verbose_name=b'screenshet')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name=b'start date')),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'status')),
                ('strategy', models.CharField(blank=True, max_length=500, null=True, verbose_name=b'strategy')),
                ('url', models.URLField(blank=True, null=True, verbose_name=b'URL')),
                ('validation', models.CharField(blank=True, max_length=500, null=True, verbose_name=b'validation')),
            ],
            options={
                'verbose_name': 'stock article tracking article',
                'verbose_name_plural': '',
            },
        ),
        migrations.CreateModel(
            name='sats_source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'description')),
                ('fail_count', models.IntegerField(blank=True, null=True, verbose_name=b'failed number')),
                ('lud_dt', models.DateField(auto_now=True, null=True, verbose_name=b'last update date')),
                ('pass_count', models.IntegerField(blank=True, null=True, verbose_name=b'passed number')),
                ('src', models.CharField(max_length=100, unique=True, verbose_name=b'source')),
                ('total_count', models.IntegerField(blank=True, null=True, verbose_name=b'total number')),
                ('url', models.URLField(blank=True, null=True, verbose_name=b'URL')),
                ('validation_count', models.IntegerField(blank=True, null=True, verbose_name=b'validated number')),
            ],
            options={
                'verbose_name': 'stock article tracking source',
                'verbose_name_plural': '',
            },
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value_5',
            field=models.DateField(blank=True, default=b'2016-05-21', null=True, verbose_name='date value'),
        ),
        migrations.AddField(
            model_name='sats_article',
            name='src',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.sats_source', to_field=b'src', verbose_name=b'source'),
        ),
    ]
