# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-21 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0069_auto_20160521_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sats_article',
            name='src',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.sats_source', to_field=b'src', verbose_name=b'source'),
        ),
    ]
