# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-21 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0072_auto_20160522_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sats_article',
            name='screenshot',
            field=models.ImageField(blank=True, default=b'../static/ledger/image/no-image.jpg', null=True, upload_to=b'../static/ledger/image/sats', verbose_name=b'screenshot'),
        ),
    ]
