# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-23 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0076_auto_20160522_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='sats_article_m',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.CharField(blank=True, max_length=500, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('product', models.CharField(blank=True, max_length=100, null=True)),
                ('product_type', models.CharField(blank=True, max_length=100, null=True)),
                ('ror', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('src_id', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('strategy', models.CharField(blank=True, max_length=500, null=True)),
                ('ticker', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('validation', models.CharField(blank=True, max_length=500, null=True)),
                ('bk_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='sats_source_m',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.CharField(blank=True, max_length=100, null=True)),
                ('fail_count', models.IntegerField(blank=True, null=True)),
                ('lud_dt', models.DateField(blank=True, null=True)),
                ('pass_count', models.IntegerField(blank=True, null=True)),
                ('src', models.CharField(blank=True, max_length=100, null=True)),
                ('total_count', models.IntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('validation_count', models.IntegerField(blank=True, null=True)),
                ('bk_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='sats_article',
            name='trend',
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value_5',
            field=models.DateField(blank=True, default=b'2016-05-23', null=True, verbose_name='date value'),
        ),
        migrations.AlterField(
            model_name='sats_article',
            name='product_type',
            field=models.CharField(blank=True, choices=[(b'shares', b'shares'), (b'funds', b'funds'), (b'others', b'others')], max_length=100, null=True, verbose_name=b'product type'),
        ),
    ]
