# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0079_auto_20160526_2334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashflow',
            options={'ordering': ['year', 'month'], 'verbose_name': 'cashflow'},
        ),
        migrations.AddField(
            model_name='cashflow',
            name='investment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'investment'),
        ),
        migrations.AddField(
            model_name='cashflow_m',
            name='investment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='dividendcard',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'Citi Dividend Card'),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='phone',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'4G contract'),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='rental',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='saving',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow_m',
            name='dividendcard',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow_m',
            name='phone',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow_m',
            name='rental',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow_m',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow_m',
            name='saving',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
