# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-18 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0081_auto_20160618_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_company',
            name='short_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'short name'),
        ),
        migrations.AddField(
            model_name='stock_company_m',
            name='short_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
