# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-18 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0082_auto_20160618_2229'),
    ]

    operations = [
        migrations.DeleteModel(
            name='stock_value_m',
        ),
        migrations.AddField(
            model_name='stock_value',
            name='avg_daily_volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name=b'avg daily volume'),
        ),
        migrations.AddField(
            model_name='stock_value',
            name='book_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name=b'book value'),
        ),
        migrations.AddField(
            model_name='stock_value',
            name='change',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name=b'change'),
        ),
        migrations.AddField(
            model_name='stock_value',
            name='dividend_share',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name=b'dividend share'),
        ),
        migrations.AddField(
            model_name='stock_value',
            name='dividend_yield',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name=b'dividend yield'),
        ),
        migrations.AddField(
            model_name='stock_value',
            name='earnings_share',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name=b'earnings share'),
        ),
        migrations.AddField(
            model_name='stock_value',
            name='ebitda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name=b'ebitda'),
        ),
        migrations.AddField(
            model_name='stock_value',
            name='market_cap',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name=b'market cap'),
        ),
        migrations.AddField(
            model_name='stock_value',
            name='prev_close',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name=b'previous close'),
        ),
        migrations.AddField(
            model_name='stock_value',
            name='price_book',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name=b'price book'),
        ),
        migrations.AddField(
            model_name='stock_value',
            name='price_earnings_growth_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name=b'price earnings growth ratio'),
        ),
        migrations.AddField(
            model_name='stock_value',
            name='price_earnings_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name=b'price earnings ratio'),
        ),
        migrations.AddField(
            model_name='stock_value',
            name='price_sales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name=b'price sales'),
        ),
        migrations.AddField(
            model_name='stock_value',
            name='short_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name=b'short ratio'),
        ),
        migrations.AddField(
            model_name='stock_value',
            name='stock_exchange',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name=b'stock exchange'),
        ),
        migrations.AddField(
            model_name='stock_value',
            name='year_high',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name=b'year high'),
        ),
        migrations.AddField(
            model_name='stock_value',
            name='year_low',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name=b'year low'),
        ),
    ]
