# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-19 09:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0083_auto_20160618_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock_value',
            old_name='price_earnings_ratio',
            new_name='pe',
        ),
        migrations.RenameField(
            model_name='stock_value',
            old_name='price_earnings_growth_ratio',
            new_name='peg',
        ),
        migrations.RemoveField(
            model_name='stock_value',
            name='dividend_share',
        ),
        migrations.RemoveField(
            model_name='stock_value',
            name='earnings_share',
        ),
        migrations.AddField(
            model_name='stock_value',
            name='dps',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name=b'dividend per share'),
        ),
        migrations.AddField(
            model_name='stock_value',
            name='eps',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name=b'earnings per share'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value_5',
            field=models.DateField(blank=True, default=b'2016-06-19', null=True, verbose_name='date value'),
        ),
        migrations.AlterField(
            model_name='stock_value',
            name='volume',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999999)], verbose_name=b'valume'),
        ),
    ]
