# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-19 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0084_auto_20160619_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_value',
            name='ebitda',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=b'ebitda'),
        ),
        migrations.AlterField(
            model_name='stock_value',
            name='market_cap',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=b'market cap'),
        ),
    ]
