# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-19 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0087_auto_20160619_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_company',
            name='remark',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name=b'remark'),
        ),
        migrations.AddField(
            model_name='stock_company',
            name='type',
            field=models.CharField(blank=True, choices=[(b'company', b'company'), (b'index', b'index')], max_length=100, null=True, verbose_name=b'type'),
        ),
        migrations.AddField(
            model_name='stock_company_m',
            name='remark',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='stock_company_m',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
