# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-25 01:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0088_auto_20160619_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock_company_simulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name=b'company')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'country')),
                ('exchange', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'exchange')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name=b'remark')),
                ('short_name', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'short name')),
                ('ticker', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name=b'ticker')),
                ('type', models.CharField(blank=True, choices=[(b'company', b'company'), (b'index', b'index')], max_length=100, null=True, verbose_name=b'type')),
            ],
            options={
                'verbose_name': 'simulation company',
            },
        ),
        migrations.CreateModel(
            name='stock_company_simulation_m',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('exchange', models.CharField(blank=True, max_length=100, null=True)),
                ('remark', models.CharField(blank=True, max_length=500, null=True)),
                ('short_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ticker', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('bk_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='stock_strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('remark', models.CharField(max_length=500)),
                ('state', models.CharField(blank=True, choices=[(b'plan', b'plan'), (b'build', b'build'), (b'simulate', b'simulate'), (b'use', b'use')], max_length=100, null=True)),
                ('strategy', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'stock strategy',
                'verbose_name_plural': 'stock strategies',
            },
        ),
        migrations.CreateModel(
            name='stock_strategy_m',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('remark', models.CharField(blank=True, max_length=500, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('strategy', models.CharField(blank=True, max_length=100, null=True)),
                ('bk_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='stock_value_simulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adj_close', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name=b'adjusted close price')),
                ('close', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name=b'close price')),
                ('date', models.DateField(blank=True, null=True, verbose_name=b'date')),
                ('high', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name=b'high')),
                ('low', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name=b'low')),
                ('open', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name=b'open price')),
                ('volume', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999999)], verbose_name=b'valume')),
                ('ticker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.stock_company_simulation', to_field=b'ticker', verbose_name=b'ticker')),
            ],
            options={
                'verbose_name': 'simulation value',
            },
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value_5',
            field=models.DateField(blank=True, default=b'2016-06-25', null=True, verbose_name='date value'),
        ),
    ]
