# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-25 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0089_auto_20160625_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='sql',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lu_date', models.DateField(auto_now=True, null=True, verbose_name=b'last update date')),
                ('sql', models.CharField(max_length=500, verbose_name=b'sql')),
            ],
            options={
                'verbose_name': 'sql',
            },
        ),
    ]
