# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-25 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0091_auto_20160626_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sql',
            name='lu_date',
        ),
    ]
