# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-06 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0092_remove_sql_lu_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='cpf_medisave',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'CPF medisave'),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='cpf_ordinary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'CPF ordinary'),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='cpf_special',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'CPF special'),
        ),
        migrations.AddField(
            model_name='cashflow_m',
            name='cpf_medisave',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='cashflow_m',
            name='cpf_ordinary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='cashflow_m',
            name='cpf_special',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='month',
            field=models.IntegerField(verbose_name=b'month'),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='rental',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'rental'),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'salary'),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='saving',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'cash savings'),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='year',
            field=models.IntegerField(verbose_name=b'year'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value_5',
            field=models.DateField(blank=True, default=b'2016-07-06', null=True, verbose_name='date value'),
        ),
    ]
