# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-06 07:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0094_auto_20160706_1544'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cashflow_old',
            new_name='cashflow_m',
        ),
    ]
