# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-06 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0095_auto_20160706_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashflow_m',
            old_name='cpf_medisave',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='cashflow',
            name='cpf_medisave',
        ),
        migrations.RemoveField(
            model_name='cashflow',
            name='cpf_ordinary',
        ),
        migrations.RemoveField(
            model_name='cashflow',
            name='cpf_special',
        ),
        migrations.RemoveField(
            model_name='cashflow',
            name='dividendcard',
        ),
        migrations.RemoveField(
            model_name='cashflow',
            name='investment',
        ),
        migrations.RemoveField(
            model_name='cashflow',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='cashflow',
            name='rental',
        ),
        migrations.RemoveField(
            model_name='cashflow',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='cashflow',
            name='saving',
        ),
        migrations.RemoveField(
            model_name='cashflow_m',
            name='cpf_ordinary',
        ),
        migrations.RemoveField(
            model_name='cashflow_m',
            name='cpf_special',
        ),
        migrations.RemoveField(
            model_name='cashflow_m',
            name='dividendcard',
        ),
        migrations.RemoveField(
            model_name='cashflow_m',
            name='investment',
        ),
        migrations.RemoveField(
            model_name='cashflow_m',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='cashflow_m',
            name='rental',
        ),
        migrations.RemoveField(
            model_name='cashflow_m',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='cashflow_m',
            name='saving',
        ),
        migrations.AddField(
            model_name='cashflow',
            name='account',
            field=models.ForeignKey(default='POSB savings', on_delete=django.db.models.deletion.PROTECT, to='ledger.account_info', to_field=b'identifier', verbose_name=b'account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashflow',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name=b'amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashflow',
            name='currency',
            field=models.CharField(default='SGD', max_length=10, verbose_name=b'currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashflow',
            name='item',
            field=models.CharField(default='POSB savings', max_length=50, verbose_name=b'item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashflow_m',
            name='account_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cashflow_m',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cashflow_m',
            name='item',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
