# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-06 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0096_auto_20160706_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='company',
            field=models.CharField(default='', max_length=50, verbose_name=b'company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashflow',
            name='number',
            field=models.CharField(default='', max_length=50, verbose_name=b'account number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashflow_m',
            name='company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cashflow_m',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
