# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-06 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0097_auto_20160706_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashflow_m',
            old_name='account_id',
            new_name='account',
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='account',
            field=models.CharField(max_length=50, verbose_name=b'account'),
        ),
    ]
