# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-13 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0098_auto_20160706_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='value_5',
            field=models.DateField(blank=True, default=b'2016-07-13', null=True, verbose_name='date value'),
        ),
    ]
