# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-14 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0101_auto_20160714_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investment_transaction',
            options={'ordering': ['date', 'identifier', 'transaction_type_1'], 'verbose_name': 'investment transaction', 'verbose_name_plural': 'investment transaction'},
        ),
    ]
