# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-14 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0102_auto_20160714_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment_transaction',
            name='transaction_type_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'transaction type 2'),
        ),
        migrations.AddField(
            model_name='investment_transaction_m',
            name='transaction_type_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
