# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-15 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0103_auto_20160714_2204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investment_transaction',
            options={'ordering': ['date', 'identifier', 'transaction_type_1', 'transaction_type_2'], 'verbose_name': 'investment transaction', 'verbose_name_plural': 'investment transaction'},
        ),
        migrations.AddField(
            model_name='investment_transaction',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name=b'price'),
        ),
        migrations.AddField(
            model_name='investment_transaction_m',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value_5',
            field=models.DateField(blank=True, default=b'2016-07-16', null=True, verbose_name='date value'),
        ),
    ]
