# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-16 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0104_auto_20160716_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='ledger_m',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(blank=True, max_length=50, null=True)),
                ('activity', models.CharField(blank=True, max_length=50, null=True)),
                ('activity_category', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('balancesheet_type', models.CharField(blank=True, max_length=50, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('gl_account', models.CharField(blank=True, max_length=50, null=True)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
                ('bk_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='account_me',
            name='account',
        ),
        migrations.DeleteModel(
            name='gl_info',
        ),
        migrations.AlterModelOptions(
            name='ledger',
            options={'ordering': ['balancesheet_type', 'gl_account'], 'verbose_name': 'general ledger'},
        ),
        migrations.AlterField(
            model_name='journal',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.account_info', to_field=b'identifier', verbose_name=b'account'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='activity',
            field=models.CharField(max_length=50, verbose_name=b'activity'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='activity_category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'activity category'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name=b'amount'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='balancesheet_type',
            field=models.CharField(choices=[(b'asset', b'asset'), (b'liability', b'liability'), (b'income', b'income'), (b'expense', b'expense')], max_length=50, verbose_name=b'ledger_type'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='currency',
            field=models.CharField(max_length=3, verbose_name=b'currency'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='date',
            field=models.DateField(verbose_name=b'date'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='journal_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'journal ID'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='last_update_date',
            field=models.DateField(auto_now=True, null=True, verbose_name=b'last update date'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='month',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'month'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='post_indicator',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name=b'posting indicator'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='reference',
            field=models.CharField(max_length=100, verbose_name=b'reference'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'remark'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'year'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.account_info', to_field=b'identifier', verbose_name=b'account'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='activity',
            field=models.CharField(max_length=50, verbose_name=b'activity'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='activity_category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'activity category'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name=b'amount'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='balancesheet_type',
            field=models.CharField(choices=[(b'asset', b'asset'), (b'liability', b'liability'), (b'income', b'income'), (b'expense', b'expense')], max_length=50, verbose_name=b'ledger type'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='currency',
            field=models.CharField(max_length=10, verbose_name=b'currency'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'remark'),
        ),
        migrations.DeleteModel(
            name='account_me',
        ),
    ]
