# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-16 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0105_auto_20160716_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal_m',
            old_name='account_id',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='ledger_m',
            old_name='account_id',
            new_name='account',
        ),
        migrations.AlterField(
            model_name='journal',
            name='account',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'account'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='account',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'account'),
        ),
    ]
