# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-16 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0107_auto_20160716_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_info',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name=b'account balance'),
        ),
        migrations.AlterField(
            model_name='investment_info',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name=b'commission'),
        ),
        migrations.AlterField(
            model_name='investment_info',
            name='current_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name=b'current value'),
        ),
        migrations.AlterField(
            model_name='investment_info',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name=b'current price'),
        ),
        migrations.AlterField(
            model_name='investment_info',
            name='dividend',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name=b'dividend'),
        ),
        migrations.AlterField(
            model_name='investment_info',
            name='last_update_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name=b'last update amount'),
        ),
        migrations.AlterField(
            model_name='investment_info',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name=b'purchasing expense'),
        ),
        migrations.AlterField(
            model_name='investment_info',
            name='profit_loss',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name=b'profit/loss'),
        ),
        migrations.AlterField(
            model_name='investment_info',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'remark'),
        ),
        migrations.AlterField(
            model_name='investment_info',
            name='sold_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name=b'selling income'),
        ),
        migrations.AlterField(
            model_name='investment_info',
            name='total_profit_loss',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name=b'net profit/loss'),
        ),
        migrations.AlterField(
            model_name='investment_info',
            name='total_yield',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name=b'yield'),
        ),
        migrations.AlterField(
            model_name='investment_info',
            name='unit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name=b'unit'),
        ),
        migrations.AlterField(
            model_name='investment_info_m',
            name='current_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='investment_info_m',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
