# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-16 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0108_auto_20160716_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment_transaction_m',
            old_name='identifier_id',
            new_name='identifier',
        ),
        migrations.AlterField(
            model_name='investment_transaction',
            name='identifier',
            field=models.CharField(max_length=50, verbose_name=b'ticker'),
        ),
    ]
