# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-17 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0109_auto_20160716_2343'),
    ]

    operations = [
        migrations.DeleteModel(
            name='stock_company_simulation_m',
        ),
        migrations.AddField(
            model_name='cashflow',
            name='owner',
            field=models.CharField(default='Awai', max_length=50, verbose_name=b'owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashflow_m',
            name='owner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='investment_info',
            name='owner',
            field=models.CharField(default='Awai', max_length=50, verbose_name=b'owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investment_info_m',
            name='owner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='investment_transaction',
            name='owner',
            field=models.CharField(default='Awai', max_length=50, verbose_name=b'owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investment_transaction_m',
            name='owner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value_5',
            field=models.DateField(blank=True, default=b'2016-07-17', null=True, verbose_name='date value'),
        ),
    ]
