# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-17 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0110_auto_20160717_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='owner',
            field=models.CharField(default='Awai', max_length=50, verbose_name=b'owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journal_m',
            name='owner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ledger',
            name='owner',
            field=models.CharField(default='Awai', max_length=50, verbose_name=b'owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ledger_m',
            name='owner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
