# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-17 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0111_auto_20160717_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment_info',
            name='identifier',
            field=models.CharField(max_length=50, verbose_name=b'ticker'),
        ),
    ]
