# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-17 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0112_auto_20160717_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='parameter_m',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_1', models.CharField(blank=True, max_length=50, null=True)),
                ('value_2', models.CharField(blank=True, max_length=100, null=True)),
                ('value_3', models.CharField(blank=True, max_length=100, null=True)),
                ('value_4', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('value_5', models.DateField(blank=True, null=True)),
                ('bk_date', models.DateField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='parameter',
            options={'verbose_name': 'parameter'},
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value_1',
            field=models.CharField(max_length=50, verbose_name=b'parameter'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'text value 1'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value_3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'text value 2'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value_4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name=b'number value'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value_5',
            field=models.DateField(blank=True, null=True, verbose_name=b'date value'),
        ),
    ]
