# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-17 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0113_auto_20160717_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_info',
            name='company',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'company'),
        ),
        migrations.AlterField(
            model_name='account_info',
            name='country',
            field=models.CharField(blank=True, default=b'Singapore', max_length=50, null=True, verbose_name=b'country'),
        ),
        migrations.AlterField(
            model_name='account_info',
            name='currency',
            field=models.CharField(blank=True, default=b'SGD', max_length=10, null=True, verbose_name=b'currency'),
        ),
        migrations.AlterField(
            model_name='account_info',
            name='identifier',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'account identifier'),
        ),
        migrations.AlterField(
            model_name='account_info',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'account number'),
        ),
        migrations.AlterField(
            model_name='account_info',
            name='owner',
            field=models.CharField(blank=True, default=b'Awai', max_length=50, null=True, verbose_name=b'owner'),
        ),
        migrations.AlterField(
            model_name='account_info',
            name='status',
            field=models.CharField(blank=True, default=b'active', max_length=50, null=True, verbose_name=b'status'),
        ),
        migrations.AlterField(
            model_name='account_info',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'type'),
        ),
    ]
