# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-17 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0114_auto_20160717_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name=b'date'),
        ),
        migrations.AddField(
            model_name='cashflow_m',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
