# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-19 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0115_auto_20160717_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashflow',
            name='number',
        ),
        migrations.RemoveField(
            model_name='cashflow_m',
            name='number',
        ),
    ]
