# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-19 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0116_auto_20160719_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='journal_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'journal ID'),
        ),
        migrations.AddField(
            model_name='cashflow_m',
            name='journal_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
