# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-22 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0117_auto_20160719_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment_info',
            name='account',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'broker account'),
        ),
        migrations.AddField(
            model_name='investment_info',
            name='broker_company',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'broker_company'),
        ),
        migrations.AddField(
            model_name='investment_info_m',
            name='account',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='investment_info_m',
            name='broker_company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='investment_transaction',
            name='account',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'broker account'),
        ),
        migrations.AddField(
            model_name='investment_transaction',
            name='broker_company',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'broker_company'),
        ),
        migrations.AddField(
            model_name='investment_transaction_m',
            name='account',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='investment_transaction_m',
            name='broker_company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
