# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-23 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0118_auto_20160722_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_strategy',
            name='remark',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stock_strategy',
            name='strategy',
            field=models.CharField(max_length=100),
        ),
    ]
