# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-23 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0119_auto_20160723_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sats_source',
            name='fail_count',
        ),
        migrations.RemoveField(
            model_name='sats_source',
            name='pass_count',
        ),
        migrations.RemoveField(
            model_name='sats_source',
            name='total_count',
        ),
        migrations.RemoveField(
            model_name='sats_source',
            name='validation_count',
        ),
        migrations.RemoveField(
            model_name='sats_source_m',
            name='fail_count',
        ),
        migrations.RemoveField(
            model_name='sats_source_m',
            name='pass_count',
        ),
        migrations.RemoveField(
            model_name='sats_source_m',
            name='total_count',
        ),
        migrations.RemoveField(
            model_name='sats_source_m',
            name='validation_count',
        ),
    ]
