# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-24 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0120_auto_20160723_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sats_article',
            name='ticker',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='ledger.stock_company', to_field=b'ticker', verbose_name=b'ticker'),
            preserve_default=False,
        ),
    ]
