# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-25 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0126_auto_20160725_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_strategy',
            name='strategy',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
