# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-14 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0128_auto_20160725_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_company',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'type'),
        ),
    ]
