# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-14 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0129_auto_20160814_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='sats_article',
            name='initial_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name=b'initial price'),
        ),
        migrations.AddField(
            model_name='sats_article_m',
            name='initial_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
