# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-23 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0130_auto_20160814_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sats_article',
            name='validation',
            field=models.CharField(blank=True, choices=[(b'min', b'min'), (b'max', b'max'), (b'between', b'between')], max_length=500, null=True, verbose_name=b'validation'),
        ),
    ]
