# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-23 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0131_auto_20160824_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_value',
            name='ticker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.stock_company', to_field=b'ticker', verbose_name=b'ticker'),
        ),
    ]
