# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-30 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0132_auto_20160824_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_table_colums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(blank=True, max_length=100, null=True)),
                ('column_name', models.CharField(blank=True, max_length=100, null=True)),
                ('verbose_name', models.CharField(blank=True, max_length=100, null=True)),
                ('verbose_name_plural', models.CharField(blank=True, max_length=100, null=True)),
                ('data_type', models.CharField(blank=True, max_length=100, null=True)),
                ('min_length', models.CharField(blank=True, max_length=100, null=True)),
                ('max_length', models.CharField(blank=True, max_length=100, null=True)),
                ('definition', models.CharField(blank=True, max_length=200, null=True)),
                ('choice_options', models.CharField(blank=True, max_length=500, null=True)),
                ('foreign_key_table', models.CharField(blank=True, max_length=200, null=True)),
                ('foreign_key_column', models.CharField(blank=True, max_length=200, null=True)),
                ('foreign_key_on_delete', models.CharField(blank=True, max_length=10, null=True)),
                ('nullable', models.CharField(blank=True, max_length=10, null=True)),
                ('blank', models.CharField(blank=True, max_length=10, null=True)),
                ('unique_key', models.CharField(blank=True, max_length=10, null=True)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('if_migrated', models.CharField(blank=True, max_length=10, null=True)),
                ('last_update_date', models.DateTimeField(auto_now=True, null=True)),
                ('model_file_name', models.CharField(blank=True, max_length=200, null=True)),
                ('table_name', models.CharField(blank=True, max_length=100, null=True)),
                ('default_value', models.CharField(blank=True, max_length=100, null=True)),
                ('auto_save_foreign_key', models.CharField(blank=True, max_length=10, null=True)),
                ('decimal_place', models.CharField(blank=True, max_length=100, null=True)),
                ('model_form', models.CharField(blank=True, max_length=100, null=True)),
                ('path', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sats_article',
            name='initial_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True, verbose_name=b'initial price'),
        ),
    ]
