# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-30 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0133_auto_20160830_2249'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='all_table_colums',
            new_name='all_table_columns',
        ),
    ]
