# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-02 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0137_auto_20160901_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_tables_m',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(blank=True, max_length=100, null=True)),
                ('model_file_name', models.CharField(blank=True, max_length=200, null=True)),
                ('table_name', models.CharField(blank=True, max_length=100, null=True)),
                ('verbose_name', models.CharField(blank=True, max_length=100, null=True)),
                ('verbose_name_plural', models.CharField(blank=True, max_length=100, null=True)),
                ('ordering', models.CharField(blank=True, max_length=200, null=True)),
                ('definition', models.CharField(blank=True, max_length=200, null=True)),
                ('if_migrated', models.CharField(blank=True, max_length=10, null=True)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('model_form', models.CharField(blank=True, max_length=10, null=True)),
                ('backup', models.CharField(blank=True, max_length=10, null=True)),
                ('unicode', models.CharField(blank=True, max_length=200, null=True)),
                ('retention_d', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('bk_date', models.DateField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='all_tables',
            options={'ordering': ['project', 'model_file_name', 'table_name'], 'verbose_name': 'all tables'},
        ),
        migrations.RemoveField(
            model_name='all_tables',
            name='last_update_date',
        ),
        migrations.AlterField(
            model_name='all_tables',
            name='backup',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=b'backup'),
        ),
        migrations.AlterField(
            model_name='all_tables',
            name='definition',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=b'definition'),
        ),
        migrations.AlterField(
            model_name='all_tables',
            name='if_migrated',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=b'if migrated'),
        ),
        migrations.AlterField(
            model_name='all_tables',
            name='model_file_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=b'model file name'),
        ),
        migrations.AlterField(
            model_name='all_tables',
            name='model_form',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=b'model form'),
        ),
        migrations.AlterField(
            model_name='all_tables',
            name='ordering',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=b'ordering'),
        ),
        migrations.AlterField(
            model_name='all_tables',
            name='project',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'project'),
        ),
        migrations.AlterField(
            model_name='all_tables',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=b'remark'),
        ),
        migrations.AlterField(
            model_name='all_tables',
            name='retention_d',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'retention days'),
        ),
        migrations.AlterField(
            model_name='all_tables',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=b'status'),
        ),
        migrations.AlterField(
            model_name='all_tables',
            name='table_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'table name'),
        ),
        migrations.AlterField(
            model_name='all_tables',
            name='unicode',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=b'unicode'),
        ),
        migrations.AlterField(
            model_name='all_tables',
            name='verbose_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'verbose name'),
        ),
        migrations.AlterField(
            model_name='all_tables',
            name='verbose_name_plural',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'verbose name plural'),
        ),
    ]
