# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-02 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0138_auto_20160902_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_tables',
            name='last_update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='all_tables_m',
            name='last_update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
