# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-02 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0140_auto_20160902_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_table_columns',
            name='column_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'column name'),
        ),
        migrations.AlterField(
            model_name='all_table_columns',
            name='verbose_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'verbose name'),
        ),
        migrations.AlterField(
            model_name='all_table_columns_m',
            name='column_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='all_table_columns_m',
            name='verbose_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
