# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-02 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0141_auto_20160902_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_table_columns',
            name='auto_save_foreign_key',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=b'auto save foreign key'),
        ),
        migrations.AlterField(
            model_name='all_table_columns',
            name='definition',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=b'definition'),
        ),
        migrations.AlterField(
            model_name='all_table_columns',
            name='foreign_key_column',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=b'foreign key_column'),
        ),
        migrations.AlterField(
            model_name='all_table_columns',
            name='last_update_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name=b'last update date'),
        ),
        migrations.AlterField(
            model_name='all_table_columns_m',
            name='auto_save_foreign_key',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='all_table_columns_m',
            name='definition',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='all_tables',
            name='last_update_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name=b'last update_date'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'text value'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value_3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'text value'),
        ),
    ]
