# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-11 06:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0143_auto_20160910_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_table_columns',
            name='sn',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)], verbose_name=b'serial number'),
        ),
        migrations.AddField(
            model_name='all_table_columns_m',
            name='sn',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
