# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-11 06:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0144_auto_20160911_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='all_table_columns',
            options={'ordering': ['project', 'model_file_name', 'table_name', 'sn', 'column_name'], 'verbose_name': 'all table columns'},
        ),
    ]
