# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-11 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0146_auto_20160911_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'verbose_name': 'journal', 'verbose_name_plural': 'journals'},
        ),
    ]
