# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-11 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0147_auto_20160911_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='balancesheet_type',
            field=models.CharField(choices=[(b'asset', b'asset'), (b'liability', b'liability'), (b'income', b'income'), (b'expense', b'expense')], max_length=50, verbose_name=b'ledger type'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='post_indicator',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name=b'post indicator'),
        ),
    ]
