# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-11 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0148_auto_20160911_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_table_functions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'projec')),
                ('model_file_name', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'model file name')),
                ('table_name', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'table name')),
                ('function', models.CharField(blank=True, max_length=999999, null=True, verbose_name=b'function')),
            ],
        ),
    ]
