# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-11 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0149_all_table_functions'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_table_functions_m',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(blank=True, max_length=100, null=True)),
                ('model_file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('table_name', models.CharField(blank=True, max_length=100, null=True)),
                ('function', models.CharField(blank=True, max_length=999999, null=True)),
                ('bk_date', models.DateField()),
            ],
        ),
    ]
