# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-11 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0150_all_table_functions_m'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sats_barchart',
            options={'ordering': ['date', 'ticker'], 'verbose_name': 'barchart source'},
        ),
        migrations.AlterModelOptions(
            name='sats_source',
            options={'ordering': ['src'], 'verbose_name': 'stock article tracking source'},
        ),
        migrations.RenameField(
            model_name='sats_barchart_m',
            old_name='initial_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='sats_barchart',
            name='initial_date',
        ),
        migrations.RemoveField(
            model_name='sats_barchart',
            name='initial_price',
        ),
        migrations.RemoveField(
            model_name='sats_barchart',
            name='max_date',
        ),
        migrations.RemoveField(
            model_name='sats_barchart',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='sats_barchart',
            name='min_date',
        ),
        migrations.RemoveField(
            model_name='sats_barchart',
            name='min_price',
        ),
        migrations.RemoveField(
            model_name='sats_barchart_m',
            name='initial_price',
        ),
        migrations.RemoveField(
            model_name='sats_barchart_m',
            name='max_date',
        ),
        migrations.RemoveField(
            model_name='sats_barchart_m',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='sats_barchart_m',
            name='min_date',
        ),
        migrations.RemoveField(
            model_name='sats_barchart_m',
            name='min_price',
        ),
        migrations.AddField(
            model_name='sats_article',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name=b'date'),
        ),
        migrations.AddField(
            model_name='sats_article_m',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sats_barchart',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name=b'date'),
        ),
        migrations.AlterField(
            model_name='sats_barchart',
            name='m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name=b'last month opinion change'),
        ),
        migrations.AlterField(
            model_name='sats_barchart',
            name='t2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name=b'today opinion change'),
        ),
        migrations.AlterField(
            model_name='sats_barchart',
            name='w2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name=b'last week opinion change'),
        ),
        migrations.AlterField(
            model_name='sats_barchart',
            name='y1',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name=b'yesterday opinion'),
        ),
        migrations.AlterField(
            model_name='sats_barchart',
            name='y2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name=b'yesterday opinion change'),
        ),
        migrations.AlterField(
            model_name='sats_source',
            name='descr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'descriptio'),
        ),
    ]
