# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-11 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0151_auto_20160912_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='sats_article',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True, verbose_name=b'max price'),
        ),
        migrations.AddField(
            model_name='sats_article',
            name='max_price_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'max price date'),
        ),
        migrations.AddField(
            model_name='sats_article',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True, verbose_name=b'min price'),
        ),
        migrations.AddField(
            model_name='sats_article',
            name='min_price_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'min price date'),
        ),
        migrations.AddField(
            model_name='sats_article_m',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sats_article_m',
            name='max_price_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sats_article_m',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sats_article_m',
            name='min_price_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sats_article',
            name='lower_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True, verbose_name=b'lower price'),
        ),
        migrations.AlterField(
            model_name='sats_article',
            name='upper_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True, verbose_name=b'upper price'),
        ),
        migrations.AlterField(
            model_name='sats_article_m',
            name='lower_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='sats_article_m',
            name='upper_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
    ]
