# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-21 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0154_auto_20160917_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='mode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'mode'),
        ),
        migrations.AddField(
            model_name='cashflow_m',
            name='mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
