# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-22 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0155_auto_20161221_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='mode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'mode'),
        ),
        migrations.AddField(
            model_name='journal_m',
            name='mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
