# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-23 02:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0156_auto_20161222_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='test',
        ),
        migrations.RemoveField(
            model_name='journal_m',
            name='test',
        ),
    ]
