# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-23 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0157_auto_20161223_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledger_m',
            old_name='test',
            new_name='mode',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='test',
        ),
        migrations.AddField(
            model_name='ledger',
            name='mode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'mode'),
        ),
    ]
