# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-25 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0158_auto_20161223_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment_transaction',
            name='mode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'mode'),
        ),
        migrations.AddField(
            model_name='investment_transaction_m',
            name='mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
