# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-01 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0159_auto_20161226_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment_info',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=11, null=True, verbose_name=b'commission'),
        ),
        migrations.AlterField(
            model_name='investment_info',
            name='current_amount',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=11, null=True, verbose_name=b'current value'),
        ),
        migrations.AlterField(
            model_name='investment_info',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=11, null=True, verbose_name=b'current price'),
        ),
        migrations.AlterField(
            model_name='investment_info',
            name='dividend',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=11, null=True, verbose_name=b'dividend'),
        ),
        migrations.AlterField(
            model_name='investment_info',
            name='last_update_amount',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=11, null=True, verbose_name=b'last update amount'),
        ),
        migrations.AlterField(
            model_name='investment_info',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=11, null=True, verbose_name=b'purchasing cost'),
        ),
        migrations.AlterField(
            model_name='investment_info',
            name='profit_loss',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=11, null=True, verbose_name=b'profit/losss'),
        ),
        migrations.AlterField(
            model_name='investment_info',
            name='sold_amount',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=11, null=True, verbose_name=b'selling income'),
        ),
        migrations.AlterField(
            model_name='investment_info',
            name='total_profit_loss',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=11, null=True, verbose_name=b'net profit'),
        ),
        migrations.AlterField(
            model_name='investment_info',
            name='total_yield',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=11, null=True, verbose_name=b'yield'),
        ),
        migrations.AlterField(
            model_name='investment_info',
            name='unit',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=11, null=True, verbose_name=b'unit'),
        ),
        migrations.AlterField(
            model_name='investment_info_m',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='investment_info_m',
            name='current_amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='investment_info_m',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='investment_info_m',
            name='dividend',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='investment_info_m',
            name='last_update_amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='investment_info_m',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='investment_info_m',
            name='profit_loss',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='investment_info_m',
            name='sold_amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='investment_info_m',
            name='total_profit_loss',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='investment_info_m',
            name='total_yield',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='investment_info_m',
            name='unit',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='investment_transaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name=b'amount'),
        ),
        migrations.AlterField(
            model_name='investment_transaction',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name=b'price'),
        ),
        migrations.AlterField(
            model_name='investment_transaction',
            name='unit',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name=b'unit'),
        ),
        migrations.AlterField(
            model_name='investment_transaction_m',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='investment_transaction_m',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='investment_transaction_m',
            name='unit',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
