# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-01 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0160_auto_20170101_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='amount',
            field=models.DecimalField(decimal_places=5, max_digits=11, verbose_name=b'amount'),
        ),
        migrations.AlterField(
            model_name='cashflow_m',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=11, null=True),
        ),
    ]
