# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-02 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0161_auto_20170101_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment_info',
            name='remark',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name=b'remark'),
        ),
        migrations.AlterField(
            model_name='investment_info_m',
            name='remark',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
