# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-30 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0162_auto_20170102_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment_info',
            name='current_amount',
        ),
        migrations.RemoveField(
            model_name='investment_info',
            name='profit_loss',
        ),
        migrations.RemoveField(
            model_name='investment_info',
            name='total_profit_loss',
        ),
        migrations.RemoveField(
            model_name='investment_info_m',
            name='current_amount',
        ),
        migrations.RemoveField(
            model_name='investment_info_m',
            name='profit_loss',
        ),
        migrations.RemoveField(
            model_name='investment_info_m',
            name='total_profit_loss',
        ),
    ]
