# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-19 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0163_auto_20170130_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock_value',
            name='alpha_6',
        ),
        migrations.AddField(
            model_name='stock_value',
            name='tickerdate',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name=b'ticker date identifier'),
        ),
        migrations.AlterField(
            model_name='stock_value',
            name='adj_close',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name=b'adjusted close'),
        ),
        migrations.AlterField(
            model_name='stock_value',
            name='close',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name=b'close pric'),
        ),
        migrations.AlterField(
            model_name='stock_value',
            name='dividend_yield',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name=b'dividend y'),
        ),
        migrations.AlterField(
            model_name='stock_value',
            name='dps',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name=b'dividend p'),
        ),
        migrations.AlterField(
            model_name='stock_value',
            name='eps',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name=b'earnings p'),
        ),
        migrations.AlterField(
            model_name='stock_value',
            name='pe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name=b'price earn'),
        ),
        migrations.AlterField(
            model_name='stock_value',
            name='peg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name=b'price earn'),
        ),
        migrations.AlterField(
            model_name='stock_value',
            name='prev_close',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name=b'previous c'),
        ),
        migrations.AlterField(
            model_name='stock_value',
            name='price_sales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name=b'price sale'),
        ),
        migrations.AlterField(
            model_name='stock_value',
            name='short_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name=b'short rati'),
        ),
        migrations.AlterField(
            model_name='stock_value',
            name='stock_exchange',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name=b'stock exch'),
        ),
    ]
