# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-15 03:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0166_auto_20170219_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sats_article',
            name='descr',
        ),
        migrations.RemoveField(
            model_name='sats_article',
            name='ror',
        ),
        migrations.RemoveField(
            model_name='sats_article',
            name='screenshot',
        ),
        migrations.RemoveField(
            model_name='sats_article',
            name='url',
        ),
        migrations.RemoveField(
            model_name='sats_article',
            name='validation',
        ),
        migrations.RemoveField(
            model_name='sats_article_m',
            name='descr',
        ),
        migrations.RemoveField(
            model_name='sats_article_m',
            name='ror',
        ),
        migrations.RemoveField(
            model_name='sats_article_m',
            name='screenshot',
        ),
        migrations.RemoveField(
            model_name='sats_article_m',
            name='url',
        ),
        migrations.RemoveField(
            model_name='sats_article_m',
            name='validation',
        ),
    ]
