# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-04 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0167_auto_20170415_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='detail',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=b'detail'),
        ),
        migrations.AddField(
            model_name='cashflow_m',
            name='detail',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
