# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-18 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0168_auto_20170604_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='account_info',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='ledger.account_info', verbose_name=b'account information'),
            preserve_default=False,
        ),
    ]
