# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-18 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0169_cashflow_account_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow_m',
            name='account_info_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
