# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-18 02:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0170_cashflow_m_account_info_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashflow_m',
            old_name='account_info_id',
            new_name='account_info',
        ),
    ]
