# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-18 03:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0171_auto_20171018_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashflow_m',
            old_name='account_info',
            new_name='account_info_id',
        ),
    ]
