# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-23 03:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0172_auto_20171018_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment_transaction',
            name='investment_info',
            field=models.ForeignKey(default=57, on_delete=django.db.models.deletion.CASCADE, to='ledger.investment_info', verbose_name=b'investment information'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investment_transaction_m',
            name='investment_info_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]