# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-01-28 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0173_auto_20171023_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sats_article',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.stock_strategy', verbose_name=b'strategy'),
        ),
        migrations.AlterField(
            model_name='sats_article_m',
            name='strategy_id',
            field=models.IntegerField(blank=True, null=True),
        ),
      migrations.AlterField(
            model_name='sats_article',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.stock_company', verbose_name=b'ticker'),
        ),
        migrations.AlterField(
            model_name='sats_article_m',
            name='ticker_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
