# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-01-28 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0174_auto_20180128_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sats_article',
            name='src',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.sats_source', verbose_name=b'source'),
        ),
        migrations.AlterField(
            model_name='sats_article_m',
            name='src_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
