# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-01-28 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0175_auto_20180128_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sats_article',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.stock_strategy', verbose_name=b'strategy'),
        ),
        migrations.AlterField(
            model_name='sats_article',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.stock_company', verbose_name=b'ticker'),
        ),
    ]
