# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='map_bu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bu', models.CharField(max_length=20, unique=True, verbose_name='business unit')),
                ('desc', models.CharField(blank=True, max_length=300, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Business Unit',
                'verbose_name_plural': 'Business Units',
            },
        ),
        migrations.CreateModel(
            name='map_ledger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger', models.CharField(max_length=20, unique=True, verbose_name='ledger')),
                ('desc', models.CharField(blank=True, max_length=300, null=True, verbose_name='description')),
                ('lvl1_cat', models.CharField(blank=True, max_length=200, null=True, verbose_name='level 1 category')),
                ('lvl2_cat', models.CharField(blank=True, max_length=200, null=True, verbose_name='level 2 category')),
                ('lvl3_cat', models.CharField(blank=True, max_length=200, null=True, verbose_name='level 3 category')),
                ('lvl4_cat', models.CharField(blank=True, max_length=200, null=True, verbose_name='level 4 category')),
                ('lvl5_cat', models.CharField(blank=True, max_length=200, null=True, verbose_name='level 5 category')),
            ],
            options={
                'ordering': ['ledger', 'lvl1_cat', 'lvl2_cat', 'lvl3_cat', 'lvl4_cat', 'lvl5_cat'],
                'verbose_name': 'Ledger Book',
                'verbose_name_plural': 'Ledger Books',
            },
        ),
    ]
