# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-02 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_ledger', '0002_auto_20160423_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map_bu',
            old_name='desc',
            new_name='descr',
        ),
        migrations.RenameField(
            model_name='map_ledger',
            old_name='desc',
            new_name='descr',
        ),
    ]
