# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-02 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_ledger', '0004_auto_20160502_2023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='map_acct_rollup',
            options={'ordering': ['acct'], 'verbose_name': 'GL account list', 'verbose_name_plural': 'GL account list'},
        ),
        migrations.AlterField(
            model_name='map_acct_rollup',
            name='acct_owner',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'account owner'),
        ),
        migrations.AlterField(
            model_name='map_acct_rollup',
            name='descr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=b'description'),
        ),
        migrations.AlterField(
            model_name='map_acct_rollup',
            name='lu_date',
            field=models.DateField(auto_now=True, null=True, verbose_name=b'last update date'),
        ),
        migrations.AlterField(
            model_name='map_acct_rollup',
            name='lu_user',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'last update user'),
        ),
        migrations.AlterField(
            model_name='map_acct_rollup',
            name='lvl1_cat',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'level 1 category'),
        ),
        migrations.AlterField(
            model_name='map_acct_rollup',
            name='lvl2_cat',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'level 2 category'),
        ),
        migrations.AlterField(
            model_name='map_acct_rollup',
            name='lvl3_cat',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'level 3 category'),
        ),
        migrations.AlterField(
            model_name='map_acct_rollup',
            name='lvl4_cat',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'level 4 category'),
        ),
    ]
