# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-02 15:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_ledger', '0005_auto_20160502_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map_acct_rollup',
            name='acct',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)], verbose_name=b'GL account'),
        ),
    ]
