# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 16:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_ledger', '0006_auto_20160502_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map_acct_rollup',
            name='lvl1_cat',
        ),
        migrations.AddField(
            model_name='map_acct_rollup',
            name='purpose',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=b'purpose'),
        ),
        migrations.AddField(
            model_name='map_acct_rollup',
            name='statement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'financial statement'),
        ),
        migrations.AlterField(
            model_name='map_acct_rollup',
            name='acct',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(10000), django.core.validators.MaxValueValidator(99999)], verbose_name=b'GL account'),
        ),
        migrations.AlterField(
            model_name='map_bu',
            name='descr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=b'description'),
        ),
        migrations.AlterField(
            model_name='map_ledger',
            name='descr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=b'description'),
        ),
    ]
