# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_ledger', '0008_auto_20160504_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map_acct_rollup',
            name='lu_date',
            field=models.DateField(auto_now=True, null=True, verbose_name=b'last update date'),
        ),
    ]
